[[redirects]]
  from = "https://stoic-bhaskara-540493.netlify.app/*"
  to = "https://coursenow.wixsite.com/home"
  status = 301
  force = true

[[redirects]]
  from = "https://coursenow.org/*"
  to = "https://coursenow.wixsite.com/home"
  status = 301
  force = true
