[[redirects]]
  from = "https://eloquent-newton-15e2d2.netlify.app/*"
  to = "https://thoughtcloudacademy.wixsite.com/home"
  status = 301
  force = true

[[redirects]]
  from = "https://thoughtcloud.ml/*"
  to = "https://thoughtcloudacademy.wixsite.com/home"
  status = 301
  force = true